version: "3.8"
services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    restart: always
    #networks:
    #mynetwork:
              #ipv4_address: "10.56.1.21"
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress
    expose:
      - 9000
    #restart: always
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    expose:
      - 3306
    #restart: always
    #networks:
    #mynetwork:
          #driver: bridge
    #ipam:
