services:

  db:
    container_name: db
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - /home/lukas/data/mariadb:/var/lib/mysql
      - ./requirements/mariadb/log:/log/mariadb

    environment:
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE
        - WORDPRESS_HOST

    expose:
      - 3306
    networks:
      - inception

    entrypoint: tmp/init.sh

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - /home/lukas/data/wordpress:/var/www/html

    ports:
      - 443:443
    networks:
      - inception

    entrypoint: nginx -g "daemon off;"

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
        - /home/lukas/data/wordpress:/var/www/html

    environment:
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE
        - WORDPRESS_DOMAIN

    expose:
      - 9000
    networks:
      - inception

    entrypoint: ./init.sh

networks:
        inception:
                name: inception
                driver: bridge
