version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "443:443"
    restart: always
  wordpress:
    image: wordpress
    restart: always
  mariadb:
    image: mariadb
    restart: always
