services:

  db:
    container_name: db
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile

    volumes:
      - $HOME/data:/var/lib/mysql
      - /requirements/mariadb/log:/log/mariadb

    expose:
      - 3306
    environment:
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE
    entrypoint: tmp/init.sh

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile

    expose:
      - 443

    entrypoint: nginx -g "daemon off;"

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile

    expose:
      - 9000

    entrypoint: tail -f
