services:

  db:
    container_name: db
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - /home/lukas/data/mariadb:/var/lib/mysql
      - /requirements/mariadb/log:/log/mariadb

    environment:
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE

    expose:
      - 3306
    networks:
      - inception

    entrypoint: tmp/init.sh

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - /home/lukas/data/wordpress:/var/www/html

    expose:
      - 443
    networks:
      - inception

    entrypoint: nginx -g "daemon off;"

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
        - /home/lukas/data/:/var/www/html

    environment:
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE

    expose:
      - 9000
    networks:
      - inception

    entrypoint: ./init.sh

networks:
        inception:
                name: inception
                driver: bridge

                #volumes:
                #        v_wordpress:
                #                driver: local
                #                driver_opts:
                #                        type: none
                #                        device: /home/lukas/data/wordpress

                #        v_mariadb:
                #                driver: local
                #                driver_opts:
                #                        type: none
                #                        device: /home/lukas/data/mariadb
