services:

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - /home/lukas/data/mariadb:/var/lib/mysql
      - ./requirements/mariadb/log:/log/mariadb

    environment:
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE
        - WORDPRESS_HOST
        - MYSQL_ROOT_PASSWORD

    expose:
      - 3306
    networks:
      - inception

    entrypoint: tmp/init.sh

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - /home/lukas/data/wordpress:/var/www/html

    ports:
      - 443:443
    networks:
      - inception
    depends_on:
      - wordpress

    entrypoint: nginx -g "daemon off;"

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
        - /home/lukas/data/wordpress:/var/www/html

    environment:
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE
        - WORDPRESS_DOMAIN

    expose:
      - 9000
    networks:
      - inception
    depends_on:
      - mariadb
      - redis

    entrypoint: ./init.sh

  redis:
    container_name: redis
    build:
      context: ./requirements/redis
      dockerfile: Dockerfile
    volumes:
      - /home/lukas/data/redis:/data

    networks:
      - inception
    expose:
      - 6379

    entrypoint: redis-server

networks:
        inception:
                name: inception
                driver: bridge
