version: "3.9"
services:
  nginx:
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    restart: always
    networks:
      mynetwork:
              #ipv4_address: "10.56.1.21"
  wordpress:
    image: wordpress
    #restart: never
  mariadb:
    image: mariadb
    #restart: never
networks:
  mynetwork:
          #external: true
          #driver: bridge
    #ipam:
