version: "3.8"
services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    restart: always
    networks:
      mynetwork:
              #ipv4_address: "10.56.1.21"
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    #restart: never
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    #restart: never
networks:
  mynetwork:
          #external: true
          #driver: bridge
    #ipam:
