#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $NEXTJS_USER WITH PASSWORD '$NEXTJS_PASS';
	CREATE DATABASE $NEXTJS_DB;
	GRANT ALL PRIVILEGES ON DATABASE $NEXTJS_DB TO $NEXTJS_USER;
EOSQL

/tmp/create_tables.sh
