user nginx;
worker_processes 2;

error_log /var/log/nginx.error_log info;

events {
	worker_connections   2000;
	# use [ kqueue | rtsig | epoll | /dev/poll | select | poll ] ;
}

http {
	server {
		listen 443;
		server_name example.org www.example.org;
	}
	location / {
		root /data/www;
	}
}
