user nginx;
worker_processes 2;

error_log /var/log/nginx.error_log info;

events {
	worker_connections   2000;
	# use [ kqueue | rtsig | epoll | /dev/poll | select | poll ] ;
	use epoll;
}

http {
	index index.php index.htm index.html
	server {
		listen 443;
		root /data/www;
		server_name example.org www.example.org;

		location /foobar {
			root /data/www/foobar
		}
	}
}
